function prepareOutputFiles(options)

fid = fopen(outfile, 'at');
	fprintf(fid, '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s', ...
		'Sample Name', ...
		'Chromosome', ...
		'Start Position (bp)', ...
		'End Position (bp)', ...
		'Start Probe ID', ...
		'End Probe ID', ...
		'Length (bp)', ...
		'No. Probes', ...
		'Copy Number', ...
		'Max. Log BF' );

	for j = 1 : 7
		fprintf(fid, '\t%s', ['Log BF: State ' num2str(j-1)] );
	end
fprintf(fid, '\n');

fclose(fid);

fid = fopen(options.outfile_genotype, 'wt');
	fprintf(fid,'%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n', ...
				'ProbeName', 'Chr', 'Position', 'Log R Ratio', 'B Allele Frequency', ...
				'Copy Number', 'Max. BF', 'Generalised Genotype', 'Generalised Genotype Prob', ...
				'Diploid Genotype', 'Diploid Genotype Prob' );
fclose(fid);

fid = fopen(options.outfile_qc, 'wt');
	fprintf(fid, '%s\t%s\t%s\t%s\t%s\n', 'Sample ID', 'Chromosome', 'Outlier Rate', 'Std. Dev. LRR', 'Std. Dev. BAF');
fclose(fid);