function writeCNVtoFile(options, sampleName, chrRange, CNV)

outfile = options.outfile;
outfile_loh = options.outfile_loh;


fid = fopen(outfile, 'wt');
	fprintf(fid, '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s', ...
		'Sample Name', ...
		'Chromosome', ...
		'Start Position (bp)', ...
		'End Position (bp)', ...
		'Start Probe ID', ...
		'End Probe ID', ...
		'Length (bp)', ...
		'No. Probes', ...
		'Copy Number', ...
		'Max. Log BF' );

	for j = 1 : 7
		fprintf(fid, '\t%s', ['Log BF: State ' num2str(j-1)] );
	end
fprintf(fid, '\n');

fid2 = fopen(outfile_loh, 'wt');
	fprintf(fid2, '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s', ...
		'Sample Name', ...
		'Chromosome', ...
		'Start Position (bp)', ...
		'End Position (bp)', ...
		'Start Probe ID', ...
		'End Probe ID', ...
		'Length (bp)', ...
		'No. Probes', ...
		'Copy Number', ...
		'Max. Log BF' );

	for j = 1 : 7
		fprintf(fid2, '\t%s', ['Log BF: State ' num2str(j-1)] );
	end
fprintf(fid2, '\n');


for chrNo = chrRange

	if length(CNV) < chrNo
		continue;
	end
	
	nCNV = length(CNV{chrNo});

	if nCNV == 0
		continue;
	end

	for i = 1 : nCNV

		thisCNV = CNV{chrNo}{i};

		cnloh = thisCNV.cnloh;
		bfmax 	= max(thisCNV.delta);
		nStates = length(thisCNV.delta);
		nSnps 	= thisCNV.index(2) - thisCNV.index(1) + 1;
		cnvlen 	= thisCNV.location(2) - thisCNV.location(1) + 1;

		if cnloh == 0
			fprintf(fid, '%s\t%g\t%15.0f\t%15.0f\t%s\t%s\t%15.0f\t%g\t%g\t%g', ...
				sampleName, ...
				chrNo, ...
				thisCNV.location(1), ...
				thisCNV.location(2), ...
				thisCNV.rs{1}, ...
				thisCNV.rs{2}, ...
				cnvlen, ...
				nSnps, ...
				thisCNV.copy, ...
				bfmax );

			for j = 1 : nStates
				fprintf(fid, '\t%g', thisCNV.delta(j) );
			end
			
			fprintf(fid, '\n');
		else
			fprintf(fid2, '%s\t%g\t%15.0f\t%15.0f\t%s\t%s\t%15.0f\t%g\t%g\t%g', ...
				sampleName, ...
				chrNo, ...
				thisCNV.location(1), ...
				thisCNV.location(2), ...
				thisCNV.rs{1}, ...
				thisCNV.rs{2}, ...
				cnvlen, ...
				nSnps, ...
				thisCNV.copy, ...
				bfmax );

			for j = 1 : nStates
				fprintf(fid2, '\t%g', thisCNV.delta(j) );
			end
			
			fprintf(fid2, '\n');
		end

	end

end

fclose(fid);
fclose(fid2);
